// Pactix — SOW PDF generator.
// Outputs a clean 1-page PDF into /public/contracts/:dealId.pdf

import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { promises as fs } from "node:fs";
import path from "node:path";
import type { DealScope } from "./types";

export interface ContractInput {
  dealId: string;
  freelancerName: string;
  freelancerEmail: string;
  clientCompany: string;
  clientEmail: string;
  scope: DealScope;
  currency: string;
}

export async function generateContractPdf(input: ContractInput): Promise<string> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([612, 792]); // US Letter
  const { width } = page.getSize();

  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const margin = 54;
  let y = 740;

  const drawText = (
    text: string,
    size: number,
    fnt = font,
    color = rgb(0.08, 0.08, 0.1)
  ) => {
    page.drawText(text, { x: margin, y, size, font: fnt, color });
  };

  // Header
  drawText("STATEMENT OF WORK", 20, bold);
  y -= 28;
  drawText(`Pactix Deal #${input.dealId.slice(0, 8).toUpperCase()}`, 10, font, rgb(0.4, 0.4, 0.5));
  y -= 28;

  // Parties
  drawText("PARTIES", 11, bold);
  y -= 16;
  drawText(`Freelancer: ${input.freelancerName} <${input.freelancerEmail}>`, 10);
  y -= 14;
  drawText(`Client: ${input.clientCompany} <${input.clientEmail}>`, 10);
  y -= 24;

  // Scope
  drawText("SCOPE OF WORK", 11, bold);
  y -= 16;
  wrapText(
    input.scope.deliverables.map((d) => `• ${d}`).join("\n"),
    page,
    margin,
    y,
    width - margin * 2,
    font,
    10
  );
  y -= Math.max(24, input.scope.deliverables.length * 14);

  // Revisions & Timeline
  drawText("REVISIONS & TIMELINE", 11, bold);
  y -= 16;
  drawText(`Revisions capped at: ${input.scope.revisions}`, 10);
  y -= 14;
  drawText(`Timeline: ${input.scope.timeline}`, 10);
  y -= 24;

  // Payment Terms
  drawText("PAYMENT TERMS", 11, bold);
  y -= 16;
  const total = input.scope.amount;
  const deposit = total * input.scope.depositPct;
  drawText(`Total: ${fmt(total, input.currency)}`, 10);
  y -= 14;
  drawText(
    `Deposit: ${fmt(deposit, input.currency)} (${Math.round(
      input.scope.depositPct * 100
    )}%) due before work begins`,
    10
  );
  y -= 14;
  drawText(`Balance: ${fmt(total - deposit, input.currency)} due on delivery`, 10);
  y -= 14;
  drawText(
    `Work outside locked scope billed at freelancer's standard hourly rate.`,
    9,
    font,
    rgb(0.35, 0.35, 0.42)
  );
  y -= 28;

  // Signatures
  drawText("SIGNATURES", 11, bold);
  y -= 20;
  page.drawLine({
    start: { x: margin, y },
    end: { x: margin + 200, y },
    thickness: 0.5,
    color: rgb(0.2, 0.2, 0.25),
  });
  page.drawLine({
    start: { x: margin + 260, y },
    end: { x: margin + 460, y },
    thickness: 0.5,
    color: rgb(0.2, 0.2, 0.25),
  });
  y -= 12;
  drawText("Freelancer", 9, font, rgb(0.4, 0.4, 0.5));
  page.drawText("Client", {
    x: margin + 260,
    y,
    size: 9,
    font,
    color: rgb(0.4, 0.4, 0.5),
  });

  // Footer
  page.drawText(
    `Generated by Pactix • ${new Date().toISOString().split("T")[0]}`,
    {
      x: margin,
      y: 40,
      size: 8,
      font,
      color: rgb(0.55, 0.55, 0.6),
    }
  );

  const bytes = await pdf.save();
  const dir = path.join(process.cwd(), "public", "contracts");
  await fs.mkdir(dir, { recursive: true });
  const filename = `${input.dealId}.pdf`;
  await fs.writeFile(path.join(dir, filename), bytes);

  return `/contracts/${filename}`;
}

function fmt(amount: number, currency: string) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency,
    maximumFractionDigits: 2,
  }).format(amount);
}

// Minimal text wrap — splits on \n, doesn't word-wrap mid-line.
function wrapText(
  text: string,
  page: ReturnType<PDFDocument["addPage"]>,
  x: number,
  startY: number,
  _maxW: number,
  font: Awaited<ReturnType<PDFDocument["embedFont"]>>,
  size: number
) {
  const lines = text.split("\n");
  let y = startY;
  for (const line of lines) {
    page.drawText(line, { x, y, size, font, color: rgb(0.08, 0.08, 0.1) });
    y -= 14;
  }
}
