"use client";

import { useEffect, useState } from "react";
import { X, FileText, CreditCard, CheckCircle2, ExternalLink } from "lucide-react";
import { toast } from "sonner";
import { useDealStore } from "@/store/deal-store";
import { formatCurrency } from "@/lib/utils";

export function ApproveClosingModal() {
  const open = useDealStore((s) => s.approveClosingOpen);
  const closingResult = useDealStore((s) => s.closingResult);
  const setOpen = useDealStore((s) => s.setApproveClosingOpen);
  const markInvoicePaid = useDealStore((s) => s.markInvoicePaid);
  const deals = useDealStore((s) => s.deals);
  const selectedDealId = useDealStore((s) => s.selectedDealId);

  const invoice = deals
    .find((d) => d.id === selectedDealId)
    ?.invoices.find((i) => i.id === closingResult?.invoiceId);

  const [polling, setPolling] = useState(false);

  // Poll the invoice status every 3s while modal is open and not paid
  useEffect(() => {
    if (!open || !invoice || invoice.status === "paid") return;
    const interval = setInterval(async () => {
      setPolling(true);
      await fetch(`/api/invoices/${invoice.id}/status`);
      await useDealStore.getState().loadDeals();
      setPolling(false);
    }, 3000);
    return () => clearInterval(interval);
  }, [open, invoice]);

  if (!open || !closingResult) return null;

  return (
    <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-6">
      <div className="w-full max-w-5xl bg-[var(--color-panel)] border border-[var(--color-border-strong)] rounded-xl shadow-2xl flex flex-col max-h-[85vh]">
        <header className="px-5 py-4 border-b border-[var(--color-border)] flex items-center justify-between">
          <div>
            <div className="text-sm font-semibold flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-[var(--color-closer)]" />
              Contract & deposit ready
            </div>
            <div className="text-xs text-[var(--color-text-muted)] mt-0.5">
              Auto-generated by the Closer agent. Review and approve to send.
            </div>
          </div>
          <button
            onClick={() => setOpen(false)}
            className="text-[var(--color-text-dim)] hover:text-[var(--color-text)]"
          >
            <X className="w-4 h-4" />
          </button>
        </header>

        <div className="flex-1 grid grid-cols-2 divide-x divide-[var(--color-border)] overflow-hidden">
          {/* Left: PDF preview */}
          <div className="flex flex-col">
            <div className="px-4 py-2 border-b border-[var(--color-border)] flex items-center gap-2 text-xs text-[var(--color-text-muted)] uppercase tracking-wider">
              <FileText className="w-3.5 h-3.5" />
              Statement of Work
              <a
                href={closingResult.pdfUrl}
                target="_blank"
                rel="noreferrer"
                className="ml-auto text-[var(--color-accent)] flex items-center gap-1 hover:underline"
              >
                Open
                <ExternalLink className="w-3 h-3" />
              </a>
            </div>
            <iframe
              src={closingResult.pdfUrl}
              className="flex-1 bg-white"
              title="Statement of Work"
            />
          </div>

          {/* Right: Stripe + payment */}
          <div className="flex flex-col p-5 space-y-5">
            <div>
              <div className="text-xs uppercase tracking-wider text-[var(--color-text-muted)] mb-2 flex items-center gap-2">
                <CreditCard className="w-3.5 h-3.5 text-[var(--color-closer)]" />
                Stripe deposit invoice
              </div>
              <div className="border border-[var(--color-closer)]/30 bg-[var(--color-closer)]/5 rounded-lg p-4">
                {invoice ? (
                  <>
                    <div className="text-2xl font-bold">
                      {formatCurrency(invoice.amount)}
                    </div>
                    <div className="text-xs text-[var(--color-text-muted)] mt-1">
                      50% deposit · {invoice.kind}
                    </div>
                    <a
                      href={invoice.stripePaymentLink}
                      target="_blank"
                      rel="noreferrer"
                      className="mt-3 inline-block text-xs text-[var(--color-accent)] underline underline-offset-2 break-all"
                    >
                      {invoice.stripePaymentLink}
                    </a>
                  </>
                ) : (
                  <div className="text-xs text-[var(--color-text-dim)]">
                    Generating...
                  </div>
                )}
              </div>
            </div>

            {/* Live Stripe dashboard mini-panel */}
            <div>
              <div className="text-xs uppercase tracking-wider text-[var(--color-text-muted)] mb-2">
                Stripe dashboard
              </div>
              <div className="border border-[var(--color-border)] bg-[var(--color-bg)] rounded-lg p-4 font-mono text-xs">
                <div className="flex items-center justify-between mb-3">
                  <span className="text-[var(--color-text-muted)]">
                    payments.latest
                  </span>
                  {polling && (
                    <span className="text-[var(--color-warn)] text-[10px] dot-thinking">
                      polling...
                    </span>
                  )}
                </div>
                {invoice ? (
                  <div className="flex items-center justify-between">
                    <span>{formatCurrency(invoice.amount)}</span>
                    <span
                      className={
                        invoice.status === "paid"
                          ? "text-[var(--color-accept)] font-bold"
                          : "text-[var(--color-warn)]"
                      }
                    >
                      {invoice.status.toUpperCase()}
                    </span>
                  </div>
                ) : (
                  <div className="text-[var(--color-text-dim)]">
                    no invoice yet
                  </div>
                )}
              </div>
            </div>

            {invoice && invoice.status !== "paid" && (
              <button
                onClick={async () => {
                  await markInvoicePaid(invoice.id);
                  const { celebratePayment } = await import("@/lib/celebrate");
                  celebratePayment();
                  toast.success("Deposit received — deal closed");
                }}
                className="text-xs px-3 py-2 rounded-md border border-[var(--color-accept)]/30 bg-[var(--color-accept)]/10 text-[var(--color-accept)] hover:bg-[var(--color-accept)]/20"
              >
                Simulate payment (demo)
              </button>
            )}
          </div>
        </div>

        <footer className="px-5 py-3 border-t border-[var(--color-border)] flex items-center justify-end gap-2">
          <button
            onClick={() => setOpen(false)}
            className="text-sm px-4 py-2 rounded-md bg-[var(--color-accent)] text-white font-medium hover:opacity-90"
          >
            Done
          </button>
        </footer>
      </div>
    </div>
  );
}
